version: "3.8"

networks:
  dev:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_HOST: 127.0.0.1
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg-isready -U ${POSTGRES_USER}} -d ${POSTGRES_DATABASE}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 5

  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: postgres
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - dev

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
