# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: document_recognition.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x64ocument_recognition.proto\x12\x13\x44ocumentRecognition\"\x1f\n\x0f\x44ocumentRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"1\n\rDocumentReply\" \n\x0c\x44ocumentType\x12\x10\n\x0cNOT_COMPUTED\x10\x00\x32\x80\x01\n\x1a\x44ocumentRecognitionService\x12\x62\n\x16\x44ocumentClassification\x12$.DocumentRecognition.DocumentRequest\x1a\".DocumentRecognition.DocumentReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'document_recognition_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DOCUMENTREQUEST']._serialized_start=51
  _globals['_DOCUMENTREQUEST']._serialized_end=82
  _globals['_DOCUMENTREPLY']._serialized_start=84
  _globals['_DOCUMENTREPLY']._serialized_end=133
  _globals['_DOCUMENTREPLY_DOCUMENTTYPE']._serialized_start=101
  _globals['_DOCUMENTREPLY_DOCUMENTTYPE']._serialized_end=133
  _globals['_DOCUMENTRECOGNITIONSERVICE']._serialized_start=136
  _globals['_DOCUMENTRECOGNITIONSERVICE']._serialized_end=264
# @@protoc_insertion_point(module_scope)
