# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import document_recognition_pb2 as document__recognition__pb2


class DocumentRecognitionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DocumentClassification = channel.unary_unary(
                '/DocumentRecognition.DocumentRecognitionService/DocumentClassification',
                request_serializer=document__recognition__pb2.DocumentRequest.SerializeToString,
                response_deserializer=document__recognition__pb2.DocumentReply.FromString,
                )


class DocumentRecognitionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DocumentClassification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentRecognitionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DocumentClassification': grpc.unary_unary_rpc_method_handler(
                    servicer.DocumentClassification,
                    request_deserializer=document__recognition__pb2.DocumentRequest.FromString,
                    response_serializer=document__recognition__pb2.DocumentReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DocumentRecognition.DocumentRecognitionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DocumentRecognitionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DocumentClassification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DocumentRecognition.DocumentRecognitionService/DocumentClassification',
            document__recognition__pb2.DocumentRequest.SerializeToString,
            document__recognition__pb2.DocumentReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
