name: Build and run tests

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_INSTALL_DIR: 'dotnet'
    strategy:
      matrix:
        dotnet-version: [7.0.x]
    defaults:
      run:
        working-directory: ./backend/SDIA

    steps:
      - name: Copy repository
        uses: actions/checkout@v4

      - name: Cache dotnet
        id: cache-dotnet
        uses: actions/cache@v3
        with:
          path: ${{env.DOTNET_INSTALL_DIR}}
          key: ${{runner.os}}-dotnet-7
          restore-keys: ${{runner.os}}-dotnet-7 

      - name: Install dotnet
        if: ${{steps.cache-dotnet.outputs.cache-hit != 'true'}}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version  }}

      - name: Set cached dotnet path [${{env.DOTNET_INSTALL_DIR}}]
        run: echo "${{env.DOTNET_INSTALL_DIR}}" >> $ENV:GITHUB_PATH

      - name: Check installed/cached dotnet version
        run: dotnet --version

      - name: Check build
        run: dotnet build

      - name: Check tests 
        run: dotnet test
