name: Run Unit Tests

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: '/opt/hostedtoolcache/Java_Corretto_jdk/17.0.8-7.1/x64'
    steps:
      - uses: actions/checkout@v3
      - name: Cache JDK
        id: cache-jdk
        uses: actions/cache@v3
        with:
          path: ${{ env.JAVA_HOME }} 
          key: ${{ runner.os }}-jdk-17
      - name: Install Java 
        if: ${{ steps.cache-jdk.outputs.cache-hit != 'true' }}
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "corretto"
          cache: gradle
            
      - name: Run the tests
        working-directory: ./backend
        run: ./gradlew test 
